#!/usr/bin/sh
VPN_USER="namhoanghai@admicro.vn"
VPN_PASSWORD="$(oathtool -b --totp 'MFCVJCT7GDZXH57PJIRQETWVZRBUONMX')%KdoujEsbAo27oCUH#Ig"
CONFIG_FILE=~/DE_internship/client-admicro-bigdata/admicro-bigdata.ovpn
echo 28122002 | sudo -S bash -c 'openvpn --config '"$CONFIG_FILE"' --auth-user-pass <(echo -e "'"$VPN_USER"'\n'"$VPN_PASSWORD"'")'
